source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

# Gems for Testing
gem 'rspec'
gem 'guard'
gem 'guard-rspec', require: false